# Generated by Django 4.1.2 on 2022-11-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0003_remove_cartitem_coupon"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="coupon_discount",
            field=models.IntegerField(null=True),
        ),
    ]
