# Generated by Django 4.1.2 on 2022-11-26 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0004_cartitem_coupon_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="offer_discount",
            field=models.IntegerField(null=True),
        ),
    ]
