# Generated by Django 4.1.2 on 2022-11-11 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0002_color_size_variations"),
    ]

    operations = [
        migrations.AddField(
            model_name="size",
            name="color",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="category.color",
            ),
            preserve_default=False,
        ),
    ]
