# Generated by Django 4.1.2 on 2022-12-03 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0003_size_color"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="variations",
            name="size",
        ),
    ]
