# Generated by Django 4.1.2 on 2022-12-04 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0005_variations_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variations",
            name="color",
            field=models.CharField(
                choices=[("Red", "Red"), ("Blue", "Blue"), ("Green", "Green")],
                default=0,
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="variations",
            name="size",
            field=models.CharField(
                choices=[("Small", "Small"), ("Medium", "Medium"), ("Large", "Large")],
                default=0,
                max_length=100,
            ),
            preserve_default=False,
        ),
    ]
