# Generated by Django 4.1.2 on 2022-12-04 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0006_alter_variations_color_alter_variations_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variations",
            name="color",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="category.color",
            ),
        ),
        migrations.AlterField(
            model_name="variations",
            name="size",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="category.size",
            ),
        ),
    ]
