# Generated by Django 4.1.2 on 2022-11-19 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0002_coupon"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Coupon",
        ),
    ]
