# Generated by Django 4.1.2 on 2022-11-27 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0004_coupon_reviewcoupon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coupon",
            name="coupon_limit",
        ),
    ]
